## YAML Template.
---
name: WMABroadcast
main: WMABroadcast.WMABroadcast
version: 0.0.1
commands:
    reloadbroadcast:
        description: Used to reload the interval and messages for the server broadcasts.